# -*- coding: utf-8 -*-
"""1227050002_AchmadAjiePriyajie_UTS_PrakML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Mf2qCAHkAKclca73NZpgrflbGDcC4Og

# Import Library
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
import seaborn as sns
import matplotlib.pyplot as plt

"""# Load Dataset"""

from google.colab import drive
drive.mount('/content/drive', force_remount= True)

df = pd.read_csv('drive/MyDrive/dataset_buys_comp.csv', encoding='latin-1')
df.head()

df.count()

df.info()

df.value_counts()

"""# Preprocessing"""

le = LabelEncoder()
for col in ['Age', 'Income', 'Student', 'Credit_Rating']:
    df[col] = le.fit_transform(df[col])

df.head()

"""# Split Dataset"""

X = df.drop('Buys_Computer', axis=1)
y = df['Buys_Computer']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""# Modeling dengan Naive Bayes"""

model = GaussianNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

"""# Evaluasi"""

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Tidak Layak', 'Layak'], yticklabels=['Tidak Layak', 'Layak'])
plt.xlabel('Prediksi')
plt.ylabel('Aktual')
plt.title('Confusion Matrix')
plt.show()

print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=['Tidak Layak', 'Layak']))

print("Accuracy:", accuracy_score(y_test, y_pred))